kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "buildkit.fullname" . }}-cache
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  {{ if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className | quote }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  accessModes: {{ .Values.storage.accessModes | toYaml | nindent 4 }}
