apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "buildkit.fullname" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  {{ if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  serviceName: {{ include "buildkit.fullname" . }}
  selector:
    matchLabels:
      {{- include "buildkit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: unconfined
        {{- with .Values.podAnnotations -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "buildkit.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
        {{ if and .Values.init.fixSysctl.enabled (eq .Values.init.fixSysctl.mode "securityContext") }}
        sysctls:
        - name: kernel.keys.maxbytes
          value: {{ .Values.init.fixSysctl.maxbytes | quote }}
        - name: kernel.keys.maxkeys
          value: {{ .Values.init.fixSysctl.maxkeys | quote }}
        {{ end }}
      
      initContainers:
        - name: permissions-fixer
          image: alpine:3
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: cache
              mountPath: /buildkit-cache
          command:
            - sh
            - -c
            - (chown 1000:1000 /buildkit-cache; chmod 0755 /buildkit-cache;)
        {{ if and .Values.init.fixSysctl.enabled (eq .Values.init.fixSysctl.mode "initContainer") }}
        - name: init-sysctl
          image: busybox
          imagePullPolicy: Always
          command:
          - sh
          - -c
          - |
            echo "Setting kernel parameters"
            echo {{ .Values.init.fixSysctl.maxbytes }} > /proc/sys/kernel/keys/maxbytes
            echo {{ .Values.init.fixSysctl.maxkeys }} > /proc/sys/kernel/keys/maxkeys
          securityContext:
            privileged: true
        {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/buildkit
            - mountPath: /home/user/.local/share/buildkit
              name: cache
          {{- if .Values.tls.enabled }}
            - name: certs
              readOnly: true
              mountPath: /certs
          {{- end }}
          args:
            - --addr
            - unix:///run/user/1000/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --oci-worker-no-process-sandbox
          {{- if .Values.tls.enabled }}
            - --tlscacert
            - /certs/ca.pem
            - --tlscert
            - /certs/cert.pem
            - --tlskey
            - /certs/key.pem
          {{- end }}
          {{- if .Values.debugLog }}
            - --debug
          {{- end }}
          ports:
            - name: tcp
              containerPort: 1234
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 60
            failureThreshold: 15
          securityContext:
            seccompProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "buildkit.fullname" . }}-buildkitd
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "buildkit.fullname" . }}-cache
        {{- if .Values.tls.enabled }}
        - name: certs
          secret:
            secretName: {{ or .Values.tls.secretName (include "buildkit.fullname" .) }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: cache
      spec:
        {{ if .Values.storage.className }}
        storageClassName: {{ .Values.storage.className | quote }}
        {{ end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
        accessModes: {{ .Values.storage.accessModes | toYaml | nindent 10 }}
    
