apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-rest
  labels:
    app: clamav-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav-rest
  template:
    metadata:
      labels:
        app: clamav-rest
    spec:
      containers:
        - name: clamav-rest-api
          # Run this image
          image: "{{ .Values.clamavRest.image.name }}:{{ .Values.clamavRest.image.version }}"
          securityContext:
            runAsUser: 1000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: node-env
            - name: CLAMD_IP
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: clamd-ip
            - name: APP_FORM_KEY
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: app-form-key
            - name: APP_MAX_FILE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: app-max-file-size
          ports:
            - containerPort: 3000
              protocol: TCP
              name: clamav-rest
---
apiVersion: v1
kind: Service
metadata:
  name: clamav-rest
spec:
  type: NodePort
  selector:
    app: clamav-rest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: clamav-rest
      nodePort: 30080
