apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-rest
  labels:
    app: clamav-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav-rest
  template:
    metadata:
      labels:
        app: clamav-rest
    spec:
      containers:
        - name: clamav-rest-api
          image: "{{ .Values.clamavRest.image.name }}:{{ .Values.clamavRest.image.version }}"
          securityContext:
            runAsUser: 1000
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 300m
              memory: 500Mi
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: node-env
            - name: CLAMD_IP
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: clamd-ip
            - name: APP_FORM_KEY
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: app-form-key
            - name: APP_MAX_FILE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: clamav-rest-configmap
                  key: app-max-file-size
          ports:
            - containerPort: 3000
              protocol: TCP
              name: clamav-rest
---
apiVersion: v1
kind: Service
metadata:
  name: clamav-rest
spec:
  selector:
    app: clamav-rest
  ports:
    - protocol: TCP
      port: 80
      targetPort: clamav-rest
      name: clamav-rest-port
