apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamavd
  labels:
    app: clamavd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamavd
  template:
    metadata:
      labels:
        app: clamavd
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: clamavd
          image: "{{ .Values.clamavd.image.name }}:{{ .Values.clamavd.image.version }}"
          command: ["/init-unprivileged"]
          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "1"
              memory: 4Gi
          ports:
            - containerPort: 3310
              protocol: TCP
              name: clamavd-port
          volumeMounts:
            - name: clamavd-conf
              mountPath: "/etc/clamav/clamd.conf"
              subPath: "clamd.conf"
      volumes:
        - name: clamavd-conf
          configMap:
            name: clamavd-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: clamavd-service
spec:
  selector:
    app: clamavd
  ports:
    - protocol: TCP
      port: 3310
      targetPort: 3310
