env: []
envFrom: []

config:
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
#   OAUTH2_PROXY_SCOPE: "user:email"
#   OAUTH2_PROXY_PROVIDER: github
#   OAUTH2_PROXY_GITHUB_ORG: SocialGouv
#   OAUTH2_PROXY_BANNER: FCE databases private access
#   OAUTH2_PROXY_FOOTER: SocialGouv auth
#   OAUTH2_PROXY_EMAIL_DOMAINS: "*"
#   OAUTH2_PROXY_COOKIE_SECURE: "false"
#   OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "https://socialgouv.github.io/support/_media/marianne.jpeg"

ingress:
  enabled: true
  annotations: {}

upstream:

host:

additionalArgs: []
replicas: 1

annotations:
  kontinuous/plugin.zeroDowntimeHandled: true

image:
  name: quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.6.0
