apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: {{ include "common.names.fullname" . }}
    application: {{ include "common.names.fullname" . }}
  name: {{ include "common.names.fullname" . }}
  annotations:
    {{ if .Values.annotations }}
    {{ range $key, $val := .Values.annotations }}
    "{{ $key }}": {{ $val | quote }}
    {{ end }}
    {{ end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: {{ include "common.names.fullname" . }}
  template:
    metadata:
      labels:
        component: {{ include "common.names.fullname" . }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          args:
            - --upstream
            - {{ .Values.upstream }}
            {{- if gt (len .Values.additionalArgs) 0 }}
            {{- tpl (.Values.additionalArgs | toYaml) . | nindent 12 }}
            {{- end }}
          name: app
          ports:
            - containerPort: 4180
              name: http
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.2
              memory: 128Mi
          livenessProbe:
            failureThreshold: 15
            httpGet:
              path: "/ping"
              port: http
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 15
            httpGet:
              path: "/ping"
              port: http
            initialDelaySeconds: 1
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: "/ping"
              port: http
            periodSeconds: 5
            initialDelaySeconds: 30
          env:
            - name: "OAUTH2_PROXY_REDIRECT_URL"
              value: https://{{ tpl (or .Values.host (print .Chart.Name "-" (or .Values.global.host ""))) . }}/oauth2/callback
            {{- if gt (len .Values.env) 0 }}
            {{- tpl (.Values.env | toYaml) . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if gt (len .Values.envFrom) 0 }}
            {{- tpl (.Values.envFrom | toYaml) . | nindent 12 }}
            {{- end }}
          
