{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .Values.ingress.annotations }}
    {{ range $key, $val := (merge dict .Values.ingress.annotations) }}
    "{{ $key }}": {{ $val | quote }}
    {{ end }}
    {{ end }}
  labels:
    component: {{ include "common.names.fullname" . }}
    application: {{ include "common.names.fullname" . }}
  name: {{ include "common.names.fullname" . }}
spec:
  rules:
    - host: >-
        {{- tpl (or .Values.host (print .Chart.Name "-" (or .Values.global.host ""))) . | nindent 8 }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - >-
          {{- tpl (or .Values.host (print .Chart.Name "-" (or .Values.global.host ""))) . | nindent 12 }}
      {{- if .Values.certSecretName }}
      secretName: {{ .Values.certSecretName }}
      {{- else }}
      secretName: {{ print .Chart.Name "-crt" }}
      {{- end }}
{{- end }}