apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ include "common.names.fullname" . }}
    application: {{ include "common.names.fullname" . }}
  name: {{ include "common.names.fullname" . }}
  annotations: {}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 4180
  selector:
    component: {{ include "common.names.fullname" . }}
  type: ClusterIP
