global: {}

replicaCount: 1
image:
  repository: "dpage/pgadmin4"
  tag: "8.5"
  pullPolicy: "Always"
namespace:
host:
defaultUser:
  email: admin@example.org
  password: password
# secrets:
#   - name: pg-app
#     keys:
#       user: PGUSER
#       password: PGPASSWORD
#       host: PGHOST
#       port: PGPORT
#       database: PGDATABASE
ingress:
  enabled: false
  annotations: {}

oauth2-proxy:
  enabled: true
  upstream: https://pgadmin
  config:
    OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
    OAUTH2_PROXY_SCOPE: "user:email"
    OAUTH2_PROXY_PROVIDER: github
    OAUTH2_PROXY_GITHUB_ORG: SocialGouv
    OAUTH2_PROXY_BANNER: FCE databases private access
    OAUTH2_PROXY_FOOTER: SocialGouv auth
    OAUTH2_PROXY_EMAIL_DOMAINS: "*"
    OAUTH2_PROXY_COOKIE_SECURE: "false"
    OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "https://socialgouv.github.io/support/_media/marianne.jpeg"
