global: {}

replicaCount: 1
image:
  repository: "dpage/pgadmin4"
  tag: "8.5"
  pullPolicy: "Always"
namespace:
host:
defaultUser:
  email: admin@example.org
  password: password
# secrets:
#   - name: pg-app
#     keys:
#       user: PGUSER
#       password: PGPASSWORD
#       host: PGHOST
#       port: PGPORT
#       database: PGDATABASE
ingress:
  enabled: true
  annotations: {}
