apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ (or .Values.component .Chart.Name) | lower }}
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ (or .Values.component .Chart.Name) | lower }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ (or .Values.component .Chart.Name) | lower }}
  template:
    metadata:
      labels:
        component: {{ (or .Values.component .Chart.Name) | lower }}
    spec:
      volumes:
        - name: servers
          secret:
            secretName: pgadmin-servers
            items:
              - key: servers
                path: servers.json
        {{- range .Values.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
            items:
            - key: {{ .keys.password }}
              path: "password"
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          {{- if .Values.defaultUser }}
          env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: {{ .Values.defaultUser.email }}
          - name: PGADMIN_DEFAULT_PASSWORD
            value: {{ .Values.defaultUser.password }}
          - name: PGADMIN_LISTEN_PORT
            value: "8080"
          - name: PGADMIN_DISABLE_POSTFIX
            value: "yes"
          - name: PGADMIN_CONFIG_SERVER_MODE
            value: "False"
          - name: PGADMIN_SERVER_JSON_FILE
            value: "/secrets/pgadmin-config/servers.json"
          {{- end }}
          securityContext:
            runAsUser: 5050
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/secrets/pgadmin-config"
              name: servers
            {{- range .Values.secrets }}
            - name: {{ .name }}
              mountPath: "/secrets/servers/{{ .name }}"
            {{- end }}
