apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: generate-pgadmin-servers
spec:
  background: true
  rules:
    - name: gensecret
      match:
        any:
        {{- range $key, $secret := .Values.secrets }}
        - resources:
            kinds:
              - Secret
            names:
              - {{ $secret.name }}
        {{- end }}
      context:
      {{- range $key, $secret := .Values.secrets }}
      - name: {{ $secret.name }}_user
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.user }}"'
      - name: {{ $secret.name }}_host
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.host }}"'
      - name: {{ $secret.name }}_port
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.port }}"'
      - name: {{ $secret.name }}_password
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.password }}"'
      - name: {{ $secret.name }}_database
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ if hasSuffix "-superuser" $secret.name }}{{ trimSuffix "-superuser" $secret.name }}-app{{else}}{{ $secret.name }}{{ end }}"
          jmesPath: 'data."{{ $secret.keys.database }}"'
      {{- end }}
      generate:
        apiVersion: v1
        kind: Secret
        name: pgadmin-servers
        namespace: "{{`{{`}}request.namespace{{`}}`}}"
        data:
          stringData:
            servers: |
              {
                "Servers": {
                  {{- range $key, $secret := .Values.secrets }}
                  "{{ add1 $key }}": {
                    "Username": "{{`{{`}}base64_decode({{ $secret.name }}_user){{`}}`}}"
                    "Host": "{{`{{`}}base64_decode({{ $secret.name }}_host){{`}}`}}"
                    "Port": "{{`{{`}}base64_decode({{ $secret.name }}_port){{`}}`}}"
                    "Password": "{{`{{`}}base64_decode({{ $secret.name }}_password){{`}}`}}"
                    "Name": "{{`{{`}}base64_decode({{ $secret.name }}_database){{`}}`}}"
                  }
                  {{- end }}
                }
              }
