apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: generate-pgadmin-servers
spec:
  background: true
  rules:
    - name: gensecret
      match:
        any:
        {{- range $key, $secret := .Values.secrets }}
        - resources:
            kinds:
              - Secret
            names:
              - {{ $secret.name }}
        {{- end }}
      context:
      {{- range $key, $secret := .Values.secrets }}
      - name: {{ $secret.name | replace "-" "_" }}_user
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.user }}"'
      - name: {{ $secret.name | replace "-" "_" }}_host
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.host }}"'
      - name: {{ $secret.name | replace "-" "_" }}_port
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.port }}"'
      - name: {{ $secret.name | replace "-" "_" }}_password
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ $secret.name }}"
          jmesPath: 'data."{{ $secret.keys.password }}"'
      - name: {{ $secret.name | replace "-" "_" }}_database
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{`}}request.namespace{{`}}`}}/secrets/{{ if hasSuffix "-superuser" $secret.name }}{{ trimSuffix "-superuser" $secret.name }}-app{{else}}{{ $secret.name }}{{ end }}"
          jmesPath: 'data."{{ $secret.keys.database }}"'
      {{- end }}
      generate:
        apiVersion: v1
        kind: Secret
        name: pgadmin-servers
        namespace: "{{ or .Values.namespace .Values.global.namespace .Release.namespace }}"
        data:
          stringData:
            servers: |
              {
                "Servers": {
                  {{- range $key, $secret := .Values.secrets }}
                  "{{ add1 $key }}": {
                    "Username": "{{`{{`}}base64_decode({{ $secret.name | replace "-" "_" }}_user){{`}}`}}"
                    "Host": "{{`{{`}}base64_decode({{ $secret.name | replace "-" "_" }}_host){{`}}`}}"
                    "Port": "{{`{{`}}base64_decode({{ $secret.name | replace "-" "_" }}_port){{`}}`}}"
                    "Password": "{{`{{`}}base64_decode({{ $secret.name | replace "-" "_" }}_password){{`}}`}}"
                    "Name": "{{`{{`}}base64_decode({{ $secret.name | replace "-" "_" }}_database){{`}}`}}"
                  }
                  {{- end }}
                }
              }
