apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ (or .Values.component .Chart.Name) | lower }}
    application: {{ .Values.repositoryName }}
  name: {{ (or .Values.component .Chart.Name) | lower }}
  annotations: {}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    component: {{ (or .Values.component .Chart.Name) | lower }}
  type: ClusterIP
 
