{{- if .Values.dumpReplication.imageRclone.imagePullSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.dumpReplication.imageRclone.imagePullSecret }}
template:
    metadata:
      name: docker-credentials
      namespace: {{ .Release.Namespace }}
      type: kubernetes.io/dockerconfigjson
{{- end}}