{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ range $key, $val := .Values.ingress.annotations }}
    "{{ $key }}": {{ $val | quote }}
    {{ end }}
  labels:
    component: {{ (or .Values.component .Chart.Name) | lower }}
    application: {{ .Values.repositoryName }}
  name: {{ include "pgweb.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "pgweb.fullname" . }}
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.host | quote }}
    {{- if .Values.certSecretName }}
      secretName: {{ .Values.certSecretName }}
    {{- else }}
      secretName: {{ print (or .Values.component .Chart.Name) "-crt" }}
    {{- end }}
{{- end }}
