apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ (or .Values.component .Chart.Name) | lower }}
    application: {{ .Values.repositoryName }}
  name: {{ (or .Values.component .Chart.Name) | lower }}
  namespace: {{ .Values.namespace }}
  annotations: {}
spec:
  ports:
    - name: http
      port: 1080
      targetPort: 1080
    - name: smtp
      port: {{ .Values.servicePort }}
      targetPort: 1025
  selector:
    component: {{ (or .Values.component .Chart.Name) | lower }}
  type: ClusterIP
  