apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ (or .Values.component .Chart.Name) | lower }}
    application: {{ .Values.repositoryName }}
  name: {{ include "pgweb.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations: {}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    component: {{ include "pgweb.fullname" . }}
  type: ClusterIP
  