name: 🎁 Release Charts

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write  # Required for OIDC token generation

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
      - name: Get GitHub App Token
        id: token
        uses: SocialGouv/token-bureau@main
        with:
          token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
          audience: socialgouv

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          charts_dir: charts
          linting: off
          token: ${{ steps.token.outputs.token }}
