name: 📰 Sync Readme

on:
  push:
    branches:
      - "*"
    files:
      - "README.md"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Sync Readme.md
        run: |
          git fetch --depth=1 origin main
          git checkout main -- README.md
          git add README.md
          git push origin gh-pages