name: Sync Major Version Branch

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  cancel-in-progress: true
  group: sync-major-version-branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Set vars
        id: vars
        run: |
          MAJOR_VERSION=$(echo "${GITHUB_REF#refs/*/}" | cut -d '.' -f 1)
          echo "major-version=$MAJOR_VERSION" >> $GITHUB_OUTPUT
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}

      - name: sync-major-version-branch
        uses: socialgouv/workflows/actions/release-deeplink-version@master
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          # token: ${{ secrets.GITHUB_TOKEN }}
          toolPath: socialgouv/workflows
          version: ${{ steps.vars.outputs.major-version }}
          branch: ${{ steps.vars.outputs.major-version }}