enabled:
namespace:
host:
servicePort: 1025
certSecretName:
repositoryName:

replicaCount: 1

image:
  repository: maildev/maildev
  tag: 2.1.0
  pullPolicy: IfNotPresent

extraArgs:
#  - "--outgoing-host"
#  - "smtp.yourdomaine.com"
#  - "--outgoing-port"
#  - "25"

persistence:
  enabled:
  accessMode: ReadWriteMany
  size: 1024M
  storageClass: ""
  existingClaim: ""
  mountPath: /home/node/maildev-data

# To clean some old mails when persistence is enabled
cron:
  enabled:
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent
  schedule: "0 1 * * *"
  daysToKeep: 15

ingress:
  enabled: true
  annotations: {}

resources:
  limits:
    cpu:
    memory:
  requests:
    cpu:
    memory:
